-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 17:53:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish2_ci ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`documento` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `anho_publicacion` INT NULL DEFAULT NULL,
  `tipo_documento` ENUM('libro', 'revista') NULL DEFAULT NULL,
  `disponible` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE =  utf8mb4_spanish2_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `tipo_usuario` ENUM('socio', 'ocasional') NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE =  utf8mb4_spanish2_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`prestamo` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `id_documento` INT NULL DEFAULT NULL,
  `fecha_prestamo` DATE NULL DEFAULT NULL,
  `fecha_devolucion` DATE NULL DEFAULT NULL,
  `devuelto` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_prestamo`),
  INDEX `prestamo_ibfk_1` (`id_usuario` ASC) VISIBLE,
  INDEX `prestamo_ibfk_2` (`id_documento` ASC) VISIBLE,
  CONSTRAINT `prestamo_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `biblioteca`.`usuario` (`id_usuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `prestamo_ibfk_2`
    FOREIGN KEY (`id_documento`)
    REFERENCES `biblioteca`.`documento` (`id_documento`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4
COLLATE =  utf8mb4_spanish2_ci;

USE `biblioteca`;

DELIMITER $$
USE `biblioteca`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `biblioteca`.`prestamo_AFTER_INSERT`
AFTER INSERT ON `biblioteca`.`prestamo`
FOR EACH ROW
BEGIN
    UPDATE Documentos
    SET disponible = 0
    WHERE id_documento = NEW.id_documento;
END$$

USE `biblioteca`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `biblioteca`.`prestamo_AFTER_UPDATE`
AFTER UPDATE ON `biblioteca`.`prestamo`
FOR EACH ROW
BEGIN
	IF (new.devuelto = 1) then
    update documentos SET disponible = 1
    where id_documento = new.id_documento;
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
